In [1164]:
import numpy as np
import sympy as sp
import pandas as pd
import matplotlib.pyplot as plt

In [1165]:
N=40

m=6

X=np.zeros(N)

for i in range(1,N+1):
    X[i-1]=0.5*(1-np.cos(((i-1)/(N-1))*np.pi))

X

array([0.        , 0.00162135, 0.00647487, 0.01452909, 0.02573178,
       0.04001028, 0.05727199, 0.07740496, 0.10027862, 0.12574463,
       0.15363782, 0.18377731, 0.21596763, 0.25      , 0.28565372,
       0.32269756, 0.36089127, 0.39998715, 0.43973166, 0.47986703,
       0.52013297, 0.56026834, 0.60001285, 0.63910873, 0.67730244,
       0.71434628, 0.75      , 0.78403237, 0.81622269, 0.84636218,
       0.87425537, 0.89972138, 0.92259504, 0.94272801, 0.95998972,
       0.97426822, 0.98547091, 0.99352513, 0.99837865, 1.        ])

In [1166]:
aplha1=1
aplha2=1
eita=1

x=sp.symbols('x')
lj=sp.symbols('lj',cls=sp.Function)
lj=lj(x)

In [1167]:

#initializing coeff matrix

coeff_matrix=np.zeros((N,N,m+1))
#lj values
for i in range(N):
    coeff_matrix[i][i][0]=1

coeff_matrix   
flag=True
for i in range(1,m+1):
    if(i==1):
        for j in range(N):
            for k in range(N):
                if(j==k):
                    continue
                to_skip_array1=np.ones(N,dtype=bool)
                to_skip_array1[j]=False
                to_skip_array2=np.ones(N,dtype=bool)
                to_skip_array2[k]=False
                
                
                coeff_matrix[j][k][i]=(np.prod(X-X[j],where=to_skip_array1)/((X[j]-X[k])*np.prod(X-X[k],where=to_skip_array2)))
    else:
        for j in range(N):
            for k in range(N):
                if(j==k):
                    continue
                coeff_matrix[j][k][i]=i*(coeff_matrix[j][j][i-1]*coeff_matrix[j][k][1]-(coeff_matrix[j][k][i-1]/(X[j]-X[k])))

#diagonal elements

    for l in range(N):
        coeff_matrix[l,l,i] = -np.sum(coeff_matrix[l,:,i])


coeff_matrix.shape
    



(40, 40, 7)

In [1168]:
#for boundary conditions

a10=(coeff_matrix[0,0,1]+2)**2-(coeff_matrix[0,0,2])/2+2*(coeff_matrix[0,0,1]+2)-1
b10=-(coeff_matrix[0,0,1]+2)-2*a10*X[0]
c10=1+a10*(X[0]**2)+X[0]*(coeff_matrix[0,0,1]+2)

a11=-((coeff_matrix[0,0,1]+2)**2)
b11=1-2*a11*X[0]
c11=X[0]*(a11*X[0]-1)

a12=1/2
b12=-X[0]
c12=(X[0]**2)/2

aN0=(coeff_matrix[N-1,N-1,1]-2)**2-(coeff_matrix[N-1,N-1,2])/2+2*(coeff_matrix[N-1,N-1,1]+2)-1
bN0=-(coeff_matrix[N-1,N-1,1]+2)-2*aN0*X[N-1]
cN0=1+aN0*(X[N-1]**2)+X[N-1]*(coeff_matrix[N-1,N-1,1]+2)

aN1=-((coeff_matrix[N-1,N-1,1]+2)**2)
bN1=1-2*aN1*X[N-1]
cN1=X[N-1]*(aN1*X[N-1]-1)

aN2=1/2
bN2=-X[N-1]
cN2=(X[N-1]**2)/2




In [1169]:
#FOR BOUNDARY CONDITIONS
h10=((x-1)**2)*(a10*(x**2)+b10*x+c10)*lj
hN0=((x-1)**2)*(aN0*(x**2)+bN0*x+cN0)*lj
h11=((x-1)**2)*(a11*(x**2)+b11*x+c11)*lj
h12=((x-1)**2)*(a12*(x**2)+b12*x+c12)*lj
hN1=((x-1)**2)*(aN1*(x**2)+bN1*x+cN1)*lj
hN2=((x-1)**2)*(aN2*(x**2)+bN2*x+cN2)*lj


In [1170]:
h10

(x - 1)**2*(714334.444444461*x**2 + 1012.33333333334*x + 1.0)*lj(x)

In [1171]:
# for non boundary conditions

hj0=sp.symbols('hj0',cls=sp.Function)

denominator=((X[j]**2)*(X[j]-1)**2)
hj0=hj0(x)


#non boundry points
Xj=X[1:N-1]


hj0=((x**2)*(x-1)**2)*lj

diff_1_hj0=sp.diff(hj0,x,1)
diff_2_hj0=sp.diff(hj0,x,2)
diff_3_hj0=sp.diff(hj0,x,3)
diff_4_hj0=sp.diff(hj0,x,4)
diff_5_hj0=sp.diff(hj0,x,5)
diff_6_hj0=sp.diff(hj0,x,6)

# diff_6_hj0_val=diff_6_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1]),(lj.diff(x,2),coeff_matrix[:,1:N-1,2]),(lj.diff(x,3),coeff_matrix[:,1:N-1,3])
#                  ,(lj.diff(x,4),coeff_matrix[:,1:N-1,4]),(lj.diff(x,5),coeff_matrix[:,1:N-1,5])],(lj.diff(x,6),coeff_matrix[:,1:N-1,6])).doit()

# diff_5_hj0_val=diff_5_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1]),(lj.diff(x,2),coeff_matrix[:,1:N-1,2]),(lj.diff(x,3),coeff_matrix[:,1:N-1,3])
#                  ,(lj.diff(x,4),coeff_matrix[:,1:N-1,4]),(lj.diff(x,5),coeff_matrix[:,1:N-1,5])]).doit()
# diff_4_hj0_val=diff_4_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1]),(lj.diff(x,2),coeff_matrix[:,1:N-1,2]),(lj.diff(x,3),coeff_matrix[:,1:N-1,3])
#                  ,(lj.diff(x,4),coeff_matrix[:,1:N-1,4])]).doit()
# diff_3_hj0_val=diff_3_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1]),(lj.diff(x,2),coeff_matrix[:,1:N-1,2]),(lj.diff(x,3),coeff_matrix[:,1:N-1,3])]).doit()
# diff_2_hj0_val=diff_2_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1]),(lj.diff(x,2),coeff_matrix[:,1:N-1,2])]).doit()
# diff_1_hj0_val=diff_2_hj0.subs([(lj,coeff_matrix[:,1:N-1,0]),(x,X),(lj.diff(x,1),coeff_matrix[:,1:N-1,1])]).doit()

# diff_1_hj0_val

In [1172]:
#for boundary conditions

diff_1_h10=sp.diff(h10,x,1)
diff_2_h10=sp.diff(h10,x,2)
diff_3_h10=sp.diff(h10,x,3)
diff_4_h10=sp.diff(h10,x,4)
diff_5_h10=sp.diff(h10,x,5)
diff_6_h10=sp.diff(h10,x,6)

diff_1_hN0=sp.diff(hN0,x,1)
diff_2_hN0=sp.diff(hN0,x,2)
diff_3_hN0=sp.diff(hN0,x,3)
diff_4_hN0=sp.diff(hN0,x,4)
diff_5_hN0=sp.diff(hN0,x,5)
diff_6_hN0=sp.diff(hN0,x,6)

diff_1_h11=sp.diff(h11,x,1)
diff_2_h11=sp.diff(h11,x,2)
diff_3_h11=sp.diff(h11,x,3)
diff_4_h11=sp.diff(h11,x,4)
diff_5_h11=sp.diff(h11,x,5)
diff_6_h11=sp.diff(h11,x,6)

diff_1_h12=sp.diff(h12,x,1)
diff_2_h12=sp.diff(h12,x,2)
diff_3_h12=sp.diff(h12,x,3)
diff_4_h12=sp.diff(h12,x,4)
diff_5_h12=sp.diff(h12,x,5)
diff_6_h12=sp.diff(h12,x,6)

diff_1_hN1=sp.diff(hN1,x,1)
diff_2_hN1=sp.diff(hN1,x,2)
diff_3_hN1=sp.diff(hN1,x,3)
diff_4_hN1=sp.diff(hN1,x,4)
diff_5_hN1=sp.diff(hN1,x,5)
diff_6_hN1=sp.diff(hN1,x,6)

diff_1_hN2=sp.diff(hN2,x,1)
diff_2_hN2=sp.diff(hN2,x,2)
diff_3_hN2=sp.diff(hN2,x,3)
diff_4_hN2=sp.diff(hN2,x,4)
diff_5_hN2=sp.diff(hN2,x,5)
diff_6_hN2=sp.diff(hN2,x,6)

# diff_1_hN2_val=diff_1_hN2.subs([(x,X)]).doit()
# diff_2_hN2_val=diff_2_hN2.subs([(x,X)]).doit()
# diff_3_hN2_val=diff_3_hN2.subs([(x,X)]).doit()
# diff_4_hN2_val=diff_4_hN2.subs([(x,X)]).doit()
# diff_5_hN2_val=diff_5_hN2.subs([(x,X)]).doit()
# diff_6_hN2_val=diff_6_hN2.subs([(x,X)]).doit()

# diff_1_hN1_val=diff_1_hN1.subs([(x,X)]).doit()
# diff_2_hN1_val=diff_2_hN1.subs([(x,X)]).doit()
# diff_3_hN1_val=diff_3_hN1.subs([(x,X)]).doit()
# diff_4_hN1_val=diff_4_hN1.subs([(x,X)]).doit()
# diff_5_hN1_val=diff_5_hN1.subs([(x,X)]).doit()
# diff_6_hN1_val=diff_6_hN1.subs([(x,X)]).doit()

# diff_1_hN0_val=diff_1_hN0.subs([(x,X)]).doit()
# diff_2_hN0_val=diff_2_hN0.subs([(x,X)]).doit()
# diff_3_hN0_val=diff_3_hN0.subs([(x,X)]).doit()
# diff_4_hN0_val=diff_4_hN0.subs([(x,X)]).doit()
# diff_5_hN0_val=diff_5_hN0.subs([(x,X)]).doit()
# diff_6_hN0_val=diff_6_hN0.subs([(x,X)]).doit()

# diff_1_h12_val=diff_1_h12.subs([(x,X)]).doit()
# diff_2_h12_val=diff_2_h12.subs([(x,X)]).doit()
# diff_3_h12_val=diff_3_h12.subs([(x,X)]).doit()
# diff_4_h12_val=diff_4_h12.subs([(x,X)]).doit()
# diff_5_h12_val=diff_5_h12.subs([(x,X)]).doit()
# diff_6_h12_val=diff_6_h12.subs([(x,X)]).doit()

# diff_1_h10_val=diff_1_h10.subs([(x,X)]).doit()
# diff_2_h10_val=diff_2_h10.subs([(x,X)]).doit()
# diff_3_h10_val=diff_3_h10.subs([(x,X)]).doit()
# diff_4_h10_val=diff_4_h10.subs([(x,X)]).doit()
# diff_5_h10_val=diff_5_h10.subs([(x,X)]).doit()
# diff_6_h10_val=diff_6_h10.subs([(x,X)]).doit()

# diff_1_h11_val=diff_1_h11.subs([(x,X)]).doit()
# diff_2_h11_val=diff_2_h11.subs([(x,X)]).doit()
# diff_3_h11_val=diff_3_h11.subs([(x,X)]).doit()
# diff_4_h11_val=diff_4_h11.subs([(x,X)]).doit()
# diff_5_h11_val=diff_5_h11.subs([(x,X)]).doit()
# diff_6_h11_val=diff_6_h11.subs([(x,X)]).doit()

# diff_6_h11_val


# diff_1_hN2_val=diff_1_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1])]).doit()
# diff_2_hN2_val=diff_2_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2])]).doit()
# diff_3_hN2_val=diff_3_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3])]).doit()
# diff_4_hN2_val=diff_4_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4])]).doit()
# diff_5_hN2_val=diff_5_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5])]).doit()
# diff_6_hN2_val=diff_6_hN2.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5]),(lj.diff(x,6),coeff_matrix[:,N-1,6])]).doit()

# diff_1_hN1_val=diff_1_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1])]).doit()
# diff_2_hN1_val=diff_2_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2])]).doit()
# diff_3_hN1_val=diff_3_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3])]).doit()
# diff_4_hN1_val=diff_4_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4])]).doit()
# diff_5_hN1_val=diff_5_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5])]).doit()
# diff_6_hN1_val=diff_6_hN1.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5]),(lj.diff(x,6),coeff_matrix[:,N-1,6])]).doit()

# diff_1_hN0_val=diff_1_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1])]).doit()
# diff_2_hN0_val=diff_2_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2])]).doit()
# diff_3_hN0_val=diff_3_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3])]).doit()
# diff_4_hN0_val=diff_4_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4])]).doit()
# diff_5_hN0_val=diff_5_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5])]).doit()
# diff_6_hN0_val=diff_6_hN0.subs([(x,X),(lj,coeff_matrix[:,N-1,0]),(lj.diff(x,1),coeff_matrix[:,N-1,1]),(lj.diff(x,2),coeff_matrix[:,N-1,2]),(lj.diff(x,3),coeff_matrix[:,N-1,3]),(lj.diff(x,4),coeff_matrix[:,N-1,4]),(lj.diff(x,5),coeff_matrix[:,N-1,5]),(lj.diff(x,6),coeff_matrix[:,N-1,6])]).doit()

# diff_1_h12_val=diff_1_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1])]).doit()
# diff_2_h12_val=diff_2_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2])]).doit()
# diff_3_h12_val=diff_3_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3])]).doit()
# diff_4_h12_val=diff_4_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4])]).doit()
# diff_5_h12_val=diff_5_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5])]).doit()
# diff_6_h12_val=diff_6_h12.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5]),(lj.diff(x,6),coeff_matrix[:,0,6])]).doit()

# diff_1_h10_val=diff_1_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1])]).doit()
# diff_2_h10_val=diff_2_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2])]).doit()
# diff_3_h10_val=diff_3_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3])]).doit()
# diff_4_h10_val=diff_4_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4])]).doit()
# diff_5_h10_val=diff_5_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5])]).doit()
# diff_6_h10_val=diff_6_h10.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5]),(lj.diff(x,6),coeff_matrix[:,0,6])]).doit()

# diff_1_h11_val=diff_1_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1])]).doit()
# diff_2_h11_val=diff_2_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2])]).doit()
# diff_3_h11_val=diff_3_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3])]).doit()
# diff_4_h11_val=diff_4_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4])]).doit()
# diff_5_h11_val=diff_5_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5])]).doit()
# diff_6_h11_val=diff_6_h11.subs([(x,X),(lj,coeff_matrix[:,0,0]),(lj.diff(x,1),coeff_matrix[:,0,1]),(lj.diff(x,2),coeff_matrix[:,0,2]),(lj.diff(x,3),coeff_matrix[:,0,3]),(lj.diff(x,4),coeff_matrix[:,0,4]),(lj.diff(x,5),coeff_matrix[:,0,5]),(lj.diff(x,6),coeff_matrix[:,0,6])]).doit()




In [1173]:

eita_term=np.exp(eita*X)
eita_term

array([1.        , 1.00162266, 1.00649588, 1.01463515, 1.0260657 ,
       1.04082147, 1.05894379, 1.08047954, 1.10547888, 1.13399254,
       1.16606849, 1.20174818, 1.2410622 , 1.28402542, 1.3306316 ,
       1.38084766, 1.43460746, 1.49180553, 1.55229062, 1.61585953,
       1.68225132, 1.75114234, 1.82214221, 1.89479136, 1.96856026,
       2.04285079, 2.11700002, 2.19028654, 2.26193963, 2.33115109,
       2.39708969, 2.45891792, 2.51581056, 2.56697461, 2.61166963,
       2.64922785, 2.67907319, 2.70073817, 2.71387812, 2.71828183])

In [1174]:
diff_1_h10

(x - 1)**2*(1428668.88888892*x + 1012.33333333334)*lj(x) + (x - 1)**2*(714334.444444461*x**2 + 1012.33333333334*x + 1.0)*Derivative(lj(x), x) + (2*x - 2)*(714334.444444461*x**2 + 1012.33333333334*x + 1.0)*lj(x)

In [1175]:
#hj(xi) for boundary conditions
h10_1=np.zeros(N)
h10_1[0]=1
for i in range(N):
    exp=diff_1_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1])]).doit()
    h10_1[i]=exp2
    
h10_1

array([1010.33333333,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ])

In [1176]:
#hj(xi) for boundary conditions
h10_2=np.zeros(N)
h10_2[0]=1
for i in range(N):
    exp=diff_2_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2])]).doit()
    h10_2[i]=exp2

h10_2

array([1424621.55555559,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ])

In [1177]:
h10_3=np.zeros(N)
h10_3[0]=1
for i in range(N):
    exp=diff_3_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3])]).doit()
    h10_3[i]=exp2

h10_3

array([-8565939.33333354,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ])

In [1178]:
h10_4=np.zeros(N)
h10_4[0]=1
for i in range(N):
    exp=diff_4_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4])]).doit()
    h10_4[i]=exp2

h10_4

array([17144026.66666707,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ])

In [1179]:
h10_5=np.zeros(N)
h10_5[0]=1
for i in range(N):
    exp=diff_5_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5])]).doit()
    h10_5[i]=exp2

h10_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1180]:
h10_6=np.zeros(N)
h10_6[0]=1
for i in range(N):
    exp=diff_6_h10.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h10_6[i]=exp2

h10_6.shape

(40,)

In [1181]:
h11_6=np.zeros(N)
h11_6[0]=1
for i in range(N):
    exp=diff_6_h11.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h11_6[i]=exp2

h11_6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1182]:
h11_5=np.zeros(N)
h11_5[0]=1
for i in range(N):
    
    exp=diff_5_h11.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h11_5[i]=exp2

h11_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1183]:
h11_4=np.zeros(N)
h11_4[0]=1
for i in range(N):
    exp=diff_4_h11.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h11_4[i]=exp2

h11_4

array([-24595650.66666718,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ,         0.        ,         0.        ,
               0.        ])

In [1184]:
h11_3=np.zeros(N)
h11_3[0]=1
for i in range(N):
    exp=diff_3_h11.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h11_3[i]=exp2

h11_3

array([12297831.33333359,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ,        0.        ,        0.        ,
              0.        ])

In [1185]:
h11_2=np.zeros(N)
h11_2[0]=1
for i in range(N):
    exp=diff_2_h11.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h11_2[i]=exp2

h11_2

array([-2049641.5555556,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ,        0.       ,        0.       ,
              0.       ])

In [1186]:
h11_1=np.ones(N)
# for i in range(N):
#     exp=diff_1_h11.subs(lj,coeff_matrix[i,0,0])
#     exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
#     h11_1[i]=exp2

h11_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [1187]:
h12_1=np.zeros(N)
h12_1[0]=1
for i in range(N):
    exp=diff_1_h12.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h12_1[i]=exp2

h12_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1188]:
h12_2=np.ones(N)
# for i in range(N):
#     exp=diff_2_h12.subs(lj,coeff_matrix[i,0,0])
#     exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
#     h12_2[i]=exp2

h12_2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [1189]:
h12_3=np.zeros(N)
h12_3[0]=1
for i in range(N):
    exp=diff_3_h12.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h12_3[i]=exp2

h12_3

array([-6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.])

In [1190]:
h12_4=np.zeros(N)
h12_4[0]=1
for i in range(N):
    exp=diff_4_h12.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h12_4[i]=exp2

h12_4

array([12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.])

In [1191]:
h12_5=np.zeros(N)
h12_5[0]=1
for i in range(N):
    exp=diff_5_h12.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h12_5[i]=exp2

h12_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1192]:
h12_6=np.zeros(N)
h12_6[0]=1
for i in range(N):
    exp=diff_6_h12.subs(lj,coeff_matrix[i,0,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,0,1]),(lj.diff(x,2),coeff_matrix[i,0,2]),(lj.diff(x,3),coeff_matrix[i,0,3]),(lj.diff(x,4),coeff_matrix[i,0,4]),(lj.diff(x,5),coeff_matrix[i,0,5]),(lj.diff(x,6),coeff_matrix[i,0,6])]).doit()
    h12_6[i]=exp2

h12_6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [1193]:
hN0_6=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_6[i]=1
        continue
    exp=diff_6_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_6[i]=exp2

hN0_6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1194]:
hN0_5=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_5[i]=1
        continue
    exp=diff_5_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_5[i]=exp2

hN0_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1195]:
hN0_4=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_4[i]=1
        continue
    exp=diff_4_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_4[i]=exp2

hN0_4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1196]:
hN0_3=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_3[i]=1
        continue
    exp=diff_3_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_3[i]=exp2

hN0_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1197]:
hN0_2=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_2[i]=1
        continue
    exp=diff_2_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_2[i]=exp2

hN0_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1198]:
hN0_1=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0_1[i]=1
        continue
    exp=diff_1_hN0.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN0_1[i]=exp2

hN0_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1199]:
hN1_6=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1_6[i]=1
        continue
    exp=diff_6_hN1.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN1_6[i]=exp2

hN1_6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1200]:
hN1_5=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1_5[i]=1
        continue
    exp=diff_5_hN1.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN1_5[i]=exp2

hN1_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1201]:
hN1_4=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1_4[i]=1
        continue
    exp=diff_4_hN1.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN1_4[i]=exp2

hN1_4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1202]:
hN1_3=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1_3[i]=1
        continue
    exp=diff_3_hN1.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN1_3[i]=exp2

hN1_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1203]:
hN1_2=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1_2[i]=1
        continue
    exp=diff_2_hN1.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN1_2[i]=exp2

hN1_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1204]:
hN1_1=np.ones(N)
# for i in range(N):
#     exp=diff_1_hN1.subs(lj,coeff_matrix[i,N-1,0])
#     exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
#     hN1_1[i]=exp2

hN1_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [1205]:
hN2_6=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN2_6[i]=1
        continue
    exp=diff_6_hN2.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN2_6[i]=exp2

hN2_6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1206]:
hN2_5=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN2_5[i]=1
        continue
    exp=diff_5_hN2.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN2_5[i]=exp2

hN2_5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1207]:
hN2_4=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN2_4[i]=1
        continue
    exp=diff_4_hN2.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN2_4[i]=exp2

hN2_4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1208]:
hN2_3=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN2_3[i]=1
        continue
    exp=diff_3_hN2.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN2_3[i]=exp2

hN2_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1209]:
hN2_2=np.ones(N)
# for i in range(N):
#     exp=diff_2_hN2.subs(lj,coeff_matrix[i,N-1,0])
#     exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
#     hN2_2[i]=exp2

hN2_2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [1210]:
hN2_1=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN2_1[i]=1
        continue
    exp=diff_1_hN2.subs(lj,coeff_matrix[i,N-1,0])
    exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,N-1,1]),(lj.diff(x,2),coeff_matrix[i,N-1,2]),(lj.diff(x,3),coeff_matrix[i,N-1,3]),(lj.diff(x,4),coeff_matrix[i,N-1,4]),(lj.diff(x,5),coeff_matrix[i,N-1,5]),(lj.diff(x,6),coeff_matrix[i,N-1,6])]).doit()
    hN2_1[i]=exp2

hN2_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1.])

In [1211]:
#FOR OTHER THAN BOUNDARY CONDITION

hj0_1=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_1[i-1][i]=1
            continue
        exp=diff_1_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_1[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_1.shape

(38, 40)

In [1212]:
hj0_2=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_2[i-1][i]=1
            continue
        exp=diff_2_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_2[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_2.shape

(38, 40)

In [1213]:
hj0_3=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_3[i-1][i]=1
            continue
        exp=diff_3_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_3[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_3.shape

(38, 40)

In [1214]:
hj0_4=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_4[i-1][i]=1
            continue
        exp=diff_4_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_4[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_4.shape

(38, 40)

In [1215]:
hj0_5=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_5[i-1][i]=1
            continue
        exp=diff_5_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_5[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_5.shape

(38, 40)

In [1216]:
hj0_6=np.zeros((N-2,N))
for j in range(1,N-1):
    for i in range(N):
        if(i==j):
            hj0_6[i-1][i]=1
            continue
        exp=diff_6_hj0.subs(lj,coeff_matrix[i,j,0])
        exp2=exp.subs([(x,X[i]),(lj.diff(x,1),coeff_matrix[i,j,1]),(lj.diff(x,2),coeff_matrix[i,j,2]),(lj.diff(x,3),coeff_matrix[i,j,3]),(lj.diff(x,4),coeff_matrix[i,j,4]),(lj.diff(x,5),coeff_matrix[i,j,5]),(lj.diff(x,6),coeff_matrix[i,j,6])]).doit()
        hj0_6[j-1][i]=exp2/((X[j]**2)*(X[j]-1)**2)
hj0_6.shape

(38, 40)

In [1217]:
E_6=hj0_6
E_6=np.vstack((h10_6,h11_6,h12_6,hN0_6,hN1_6,hN2_6,E_6))
E_6.shape

(44, 40)

In [1218]:
E_5=hj0_5
E_5=np.vstack((h10_5,h11_5,h12_5,hN0_5,hN1_5,hN2_5,E_5))
E_5.shape

(44, 40)

In [1219]:
E_4=hj0_4
E_4=np.vstack((h10_4,h11_4,h12_4,hN0_4,hN1_4,hN2_4,E_4))
E_4.shape

(44, 40)

In [1220]:
E_3=hj0_3
E_3=np.vstack((h10_3,h11_3,h12_3,hN0_3,hN1_3,hN2_3,E_3))
E_3.shape

(44, 40)

In [1221]:
E_2=hj0_2
E_2=np.vstack((h10_2,h11_2,h12_2,hN0_2,hN1_2,hN2_2,E_2))
E_2.shape

(44, 40)

In [1222]:
E_1=hj0_1
E_1=np.vstack((h10_1,h11_1,h12_1,hN0_1,hN1_1,hN2_1,E_1))
E_1.shape


(44, 40)

In [1223]:
E_6=E_6.T
E_5=E_5.T
E_4=E_4.T
E_3=E_3.T
E_2=E_2.T
E_1=E_1.T

E_6.shape

(40, 44)

In [1224]:
#differential equation transformation

E_6_diff=np.zeros((N,N+4))
E_5_diff=np.zeros((N,N+4))
E_4_diff_alpha1=np.zeros((N,N+4))
E_3_diff=np.zeros((N,N+4))
E_2_diff_alpha1=np.zeros((N,N+4))

for i in range(N):
        E_6_diff[i,:]=(aplha1**2)*eita_term[i]*E_6[i,:]
        E_5_diff[i,:]=3*(aplha1**2)*eita*eita_term[i]*E_5[i,:]
        E_4_diff_alpha1[i,:]=(3*(aplha1**2)*(eita**2)-1)*eita_term[i]*E_4[i,:]
        E_3_diff[i,:]=((aplha1**2)*(eita**3)-2*eita)*eita_term[i]*E_3[i,:]
        E_2_diff_alpha1[i,:]=(eita**2)*eita_term[i]*E_2[i,:]

In [1225]:


h10=np.zeros(N)

for i in range(N):
    if(i==0):
        h10[i]=1
        continue
    h10[i]=((X[i]-1)**2)*(a10*(X[i]**2)+b10*X[i]+c10)*coeff_matrix[i,0,0]

h11=np.zeros(N)
for i in range(N):
    if(i==0):
        h11[i]=1
        continue
    h11[i]=((X[i]-1)**2)*(a11*(X[i]**2)+b11*X[i]+c11)*coeff_matrix[i,0,0]

h12=np.zeros(N)
for i in range(N):
    if(i==0):
        h12[i]=1
        continue
    h12[i]=((X[i]-1)**2)*(a12*(X[i]**2)+b12*X[i]+c12)*coeff_matrix[i,0,0]

hN0=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN0[i]=1
        continue
    hN0[i]=((X[i]-1)**2)*(aN0*(X[i]**2)+bN0*X[i]+cN0)*coeff_matrix[i,N-1,0]
hN1=np.zeros(N)
for i in range(N):
    if(i==N-1):
        hN1[i]=1
        continue
    hN1[i]=((X[i]-1)**2)*(aN1*(X[i]**2)+bN1*X[i]+cN1)*coeff_matrix[i,N-1,0]
hN2=np.zeros(N)
for i in range(N):
    if(i==0):
        hN2[i]=1
        continue
    hN2[i]=((X[i]-1)**2)*(aN2*(X[i]**2)+bN2*X[i]+cN2)*coeff_matrix[i,N-1,0]


boundary_1=np.zeros(N+4)
boundary_1[0]=1

boundary_2=E_2[0,:]
boundary_3=E_4[0,:]
boundary_4=E_4[N-1,:]
boundary_5=E_2[N-1,:]
boundary_6=np.zeros(N+4)
boundary_6[3]=1
boundary_matrix=np.vstack((boundary_1,boundary_2,boundary_3,boundary_4,boundary_5,boundary_6))
boundary_matrix

Sbb=boundary_matrix[:,0:6]
df=pd.DataFrame(Sbb)
np.linalg.inv(Sbb)



array([[ 1.00000000e+00,  0.00000000e+00, -1.23041324e-21,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.97034890e-01, -0.00000000e+00, -4.06575949e-08,
        -4.87891138e-07,  4.87891138e-07, -0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.11022302e-16,  0.00000000e+00,  1.00000000e+00],
       [-4.05012147e+03, -1.00000000e+00,  8.33334960e-02,
         1.00000195e+00, -1.95156455e-06, -1.00000000e+00],
       [ 4.05012147e+03,  1.00000000e+00, -8.33334960e-02,
        -1.95156455e-06,  1.95156455e-06,  0.00000000e+00]])

In [1226]:
S=E_6_diff+E_5_diff+E_4_diff_alpha1+E_3_diff-E_2_diff_alpha1
S.shape
Sdb=S[1:N-1,0:6]
Sdb.shape

(38, 6)

In [1227]:
Sbd=boundary_matrix[:,6:]
Sbd.shape

(6, 38)

In [1228]:
Sdd=S[1:N-1,6:]
Sdd.shape

(38, 38)

In [1229]:
Q=(aplha2**2)*E_4-E_2
Qdb=Q[1:N-1,0:6]
Qdd=Q[1:N-1,6:]

In [1230]:
term=Sdd-Sdb@np.linalg.inv(Sbb)@Sbd-Qdb@np.linalg.inv(Sbb)@Sbd
term.shape

(38, 38)

In [1231]:
np.linalg.eigvals(term)

array([ 4.00649064,  4.0259835 ,  4.05854061,  4.1042628 ,  4.16328589,
        4.23577516,  4.32191814,  4.42191553,  4.53597016,  4.66427395,
        4.80699271,  4.9642488 ,  5.13610167,  5.32252641,  5.52339064,
        5.73842986,  5.96722213,  6.20916248,  6.46343811,  6.7290053 ,
        7.00456936,  7.28856884,  7.57916544,  7.87424104,  8.17140318,
        8.46800007,  8.76114614,  9.04775851,  9.32460437,  9.58835878,
        9.83567166, 10.06324225, 10.26789846, 10.44667852, 10.59691141,
       10.71629275, 10.80295267, 10.8555125 ])